spring.application.name=BE

spring.datasource.url=jdbc:mysql://localhost:3306/college_issue_tracker
spring.datasource.username=root
spring.datasource.password=Root

huggingface.api.key=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
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

# Allow large image uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Static file serving for uploaded worker proof images
spring.web.resources.static-locations=file:uploads/,classpath:/static/
